# For more information visit the DynamicHologram's page on SpigotMC.org!
# Should DynamicHolograms show a hologram when a player sneaks and follow the player (as long as he sneaks)?
sneakHolo: false

# Should the playersHead be shown on top of the hologram?
playerHead: true

# Distance between the holograms
distance: 0.28

text:
- '&aHello my friend'
- '&bHow are you?'